/**
 * React + TypeScript + Vite 프레임워크 프롬프트 컴포넌트
 */

export function getViteTypePrompt(): string {
  return [
    '**React TypeScript + Vite 프로젝트 특화 규칙:**',
    '',
    '**중요**: 프로젝트의 package.json, tsconfig.json, vite.config.ts를 먼저 확인하여 현재 설정에 맞게 작업을 수행하세요.',
    '',
    '- 프로젝트 컨텍스트: React / TypeScript / Vite',
    '- **중요: vite.config.ts와 package.json을 먼저 확인하고, 현재 설정에 맞게 작업 수행**',
    '- package.json에서 "vite" 대신 "npx vite" 사용',
    '- **새 프로젝트 생성 시에만** package.json에 "type": "module" 필드 추가 (기존 프로젝트는 현재 설정 유지)',
    '- **필수 파일**: Vite 프로젝트를 생성할 때는 반드시 다음 파일들이 필요합니다:',
    '  * **index.html** (프로젝트 루트에 필수)',
    '  * App.tsx, App.css, index.css, main.tsx',
    '- **index.html 필수 규칙 (매우 중요)**:',
    '  * Vite 프로젝트를 새로 생성할 때는 반드시 프로젝트 루트에 index.html 파일을 생성해야 합니다.',
    '  * index.html은 Vite의 진입점이며, <script type="module" src="/src/main.tsx"></script> 같은 형태로 main.tsx를 참조해야 합니다.',
    '  * 예시: "새 파일: index.html" + 적절한 HTML 구조와 Vite 스크립트 태그 포함',
    '- **필수 플러그인**: React 프로젝트인 경우 **@vitejs/plugin-react-swc는 필수**입니다. vite.config.ts에 반드시 포함되어야 하며, package.json의 devDependencies에 추가되어야 합니다.',
    '- tsconfig.json: ES 모듈 호환 설정 필수',
    '  * module: "CommonJS"',
    '  * moduleResolution: "node"',
    '  * **"references" 필드는 절대 추가하지 마세요.** tsconfig.json에 "references": [{ "path": "./tsconfig.node.json" }] 같은 필드를 추가하지 마세요.',
    '- **경로 별칭 사용 규칙 (@/ 등)**:',
    '  * Vite/TypeScript 프로젝트에서 "@/..." 와 같은 import 별칭은 tsconfig.json 의 paths 또는 vite.config.ts 의 resolve.alias 에 실제로 정의된 경우에만 사용합니다.',
    '  * 별칭 설정이 없다면 항상 "./components/RefundLookup", "../pages/RefundLookup" 과 같이 상대 경로 import만 사용하세요.',
    '  * 별칭이 없는 프로젝트에서 "@/pages/RefundLookup" 과 같은 경로를 사용하면 "[plugin:vite:import-analysis] Failed to resolve import" 오류가 발생하므로, 이런 형식은 절대 사용하지 않습니다.',
    '- **파일/패키지 import 규칙 (매우 중요)**:',
    '  * **모든 import 문을 추가하기 전에 반드시 해당 파일이나 패키지가 실제로 존재하는지 확인하세요.**',
    '  * **파일 import 규칙**:',
    '    - 상대 경로 import(예: \'import Home from \'./pages/Home\'\')를 추가할 때는, 해당 파일이 실제로 존재하는지 먼저 확인합니다.',
    '    - 파일이 존재하지 않으면 import를 추가하지 마세요. 또는 파일을 먼저 생성한 후에 import를 추가하세요.',
    '    - "있다고 가정"하거나 "있다고 가정하고" 같은 표현을 사용하지 마세요. 실제로 존재하는 파일만 import하세요.',
    '  * **CSS 파일(App.css 등) 사용 규칙 (매우 중요)**:',
    '    - App.tsx 또는 다른 tsx 파일에서 "import \'./App.css\'" 와 같이 CSS 파일을 import 하려면, **반드시 해당 CSS 파일을 생성해야 합니다.**',
    '    - CSS import가 있으면 항상 해당 CSS 파일을 생성하세요. 예: \`import \'./RefundSearchPage.css\'\` → "새 파일: src/pages/RefundSearchPage.css" 생성',
    '    - tsx 파일을 생성할 때 CSS import가 포함되어 있으면, 같은 이름의 CSS 파일도 함께 생성하세요.',
    '    - 예: "새 파일: src/pages/RefundSearchPage.tsx"에 \`import \'./RefundSearchPage.css\'\`가 있으면 → "새 파일: src/pages/RefundSearchPage.css"도 함께 생성',
    '    - 파일이 없다면 반드시 "새 파일: src/App.css" + 전체 CSS 내용을 함께 생성해야 합니다.',
    '    - CSS 파일을 만들 계획이 없다면, 존재하지 않는 경로를 import하는 구문("import \'./App.css\'") 등을 추가하지 마세요.',
    '  * **패키지 import 규칙**:',
    '    - 외부 패키지 import(예: \'import axios from \'axios\'\')를 추가할 때는, package.json의 dependencies 또는 devDependencies에 해당 패키지가 실제로 포함되어 있는지 먼저 확인합니다.',
    '    - 패키지가 설치되지 않았다면 import를 추가하지 마세요. 또는 package.json에 패키지를 추가한 후에 import를 추가하세요.',
    '    - "있다고 가정"하거나 "설치되어 있다고 가정" 같은 표현을 사용하지 마세요. 실제로 설치된 패키지만 import하세요.',
    '- React + TypeScript 타입 정의 규칙:',
    '  * React/TypeScript 조합일 때는 package.json의 devDependencies에 최소한 다음 타입 정의 패키지가 포함되어야 합니다.',
    '    - "@types/react"',
    '    - "@types/react-dom"',
    '  * React Router, Testing Library 등 추가 React 생태계 라이브러리를 사용할 경우, 해당 라이브러리의 @types/* 패키지도 함께 devDependencies에 추가해야 합니다.',
    '  * **중요 예외: react-router-dom v6 이상은 타입이 내장되어 있습니다. @types/react-router-dom을 추가하지 마세요.**',
    '  * 코드에서 import 하는 React 관련 패키지와 package.json 의 dependencies/devDependencies, 그리고 @types/* 항목이 항상 일치하도록 관리하세요.',
    '- **필수 라이브러리 (React 프로젝트)**:',
    '  * **react-router-dom은 React 프로젝트에서 라우팅을 위해 필수 라이브러리입니다.**',
    '  * 코드에서 react-router-dom을 import하는 경우(예: import { BrowserRouter, Routes, Route } from \'react-router-dom\'),',
    '    반드시 package.json의 dependencies에 "react-router-dom"을 추가해야 합니다.',
    '  * react-router-dom을 사용하는 모든 React 프로젝트는 package.json에 이 의존성이 포함되어 있어야 합니다.',
    '- **라우터 사용 규칙 (매우 중요)**:',
    '  * **BrowserRouter는 App.tsx에만 사용하세요. main.tsx에는 절대 사용하지 마세요.**',
    '  * main.tsx는 ReactDOM.render 또는 createRoot만 사용하고, BrowserRouter를 import하거나 사용하지 마세요.',
    '  * App.tsx에서 BrowserRouter로 Routes와 Route를 감싸서 라우팅을 구현하세요.',
    '  * 예시 (올바른 구조):',
    '    - main.tsx: import App from \'./App\'; ReactDOM.createRoot(...).render(<App />);',
    '    - App.tsx: import { BrowserRouter, Routes, Route } from \'react-router-dom\'; ... <BrowserRouter><Routes>...</Routes></BrowserRouter>',
    '  * **절대 하지 말 것**: main.tsx에 BrowserRouter를 추가하거나, App.tsx와 main.tsx 둘 다에 BrowserRouter를 추가하지 마세요.',
    '- **package.json 버전 명시 규칙 (매우 중요)**:',
    '  * package.json에 패키지를 추가할 때는 **반드시 실제로 존재하는 버전을 사용**해야 합니다.',
    '  * 존재하지 않는 버전을 사용하면 "npm error code ETARGET" 또는 "No matching version found" 오류가 발생합니다.',
    '  * **"latest" 버전은 절대 사용하지 마세요.** 항상 특정 버전을 명시해야 합니다.',
    '  * 버전을 명시할 때는 다음 형식을 사용하세요:',
    '    - 특정 버전: "^1.2.3" 또는 "~1.2.3" 또는 "1.2.3" (실제로 존재하는 버전만 사용)',
    '  * 예시: eslint-config-airbnb@19.2.0은 존재하지 않는 버전입니다. 실제로 존재하는 버전(예: "^19.0.4")을 사용해야 합니다.',
    '  * **절대 사용하지 말 것**: "latest", "*", "x" 같은 범용 버전 지정자는 절대 사용하지 마세요.',
    '  * **절대 가정하지 마세요**: "19.2.0이 있을 것 같다" 같은 추측으로 버전을 명시하지 마세요. 반드시 실제로 존재하는 버전만 사용하세요.'
  ].join('\n');
}

